/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

/**
 *
 * @author Davi Daniel
 */
public class FormProdutos extends javax.swing.JPanel {

    /**
     * Creates new form FormProdutos
     */
    public FormProdutos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlNorth = new javax.swing.JPanel();
        lblPesquisa = new javax.swing.JLabel();
        txtPesquisa = new javax.swing.JTextField();
        btnPesquisa = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnAtualizarPagina = new javax.swing.JButton();
        tabelaProdutos = new javax.swing.JScrollPane();
        tblProdutos = new javax.swing.JTable();

        setMinimumSize(new java.awt.Dimension(850, 600));
        setPreferredSize(new java.awt.Dimension(850, 600));
        setLayout(new java.awt.BorderLayout());

        pnlNorth.setMinimumSize(new java.awt.Dimension(50, 50));
        pnlNorth.setPreferredSize(new java.awt.Dimension(50, 50));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10);
        flowLayout1.setAlignOnBaseline(true);
        pnlNorth.setLayout(flowLayout1);

        lblPesquisa.setText("Pesquisa:");
        pnlNorth.add(lblPesquisa);

        txtPesquisa.setPreferredSize(new java.awt.Dimension(200, 26));
        pnlNorth.add(txtPesquisa);

        btnPesquisa.setText("Procurar");
        pnlNorth.add(btnPesquisa);

        btnDeletar.setText("Deletar");
        btnDeletar.addActionListener(this::btnDeletarActionPerformed);
        pnlNorth.add(btnDeletar);

        btnEditar.setText("Editar");
        pnlNorth.add(btnEditar);

        btnAtualizarPagina.setText("Atualizar");
        pnlNorth.add(btnAtualizarPagina);

        add(pnlNorth, java.awt.BorderLayout.NORTH);

        tabelaProdutos.setPreferredSize(new java.awt.Dimension(100, 100));

        tblProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Quantidade", "Preço"
            }
        ));
        tabelaProdutos.setViewportView(tblProdutos);

        add(tabelaProdutos, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeletarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizarPagina;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnPesquisa;
    private javax.swing.JLabel lblPesquisa;
    private javax.swing.JPanel pnlNorth;
    private javax.swing.JScrollPane tabelaProdutos;
    private javax.swing.JTable tblProdutos;
    private javax.swing.JTextField txtPesquisa;
    // End of variables declaration//GEN-END:variables
}
